# Generated by Django 3.2.5 on 2021-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
